name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

  # release:
  #   types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Packaging
        run: ./release.sh
        shell: bash
        
